### ISSUE TITLE
how to debug sonatype nexus plugin

### ISSUE THREAD

**Issue by yangyang-zhang** [groupe-edf/nexus-report-plugin#32]
Hello, I want to do secondary development based on this plug-in, but I'm in the local IDEA, and I don't know how to debug，I tried to add parameters to the nexus run command，IDEA tries to connect，But obviously not。

How do you develop and debug locally

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/16460777/205199648-685af898-1241-46de-9616-708829665d98.png">

**Comment by mat1e** [comment]
To run Nexus in debug mode, run the command "nexus console debug" in "$NEXUS_HOME/bin".
On my env, I debug with Eclipse "Remote Java Application".
